### ISSUE TITLE
stuck at "TASK [Start docker containers]"

### ISSUE THREAD

**Issue by strongpower** [Altoros/Ansible-Fabric-Starter#12]
- Env: 2 hosts, both are ubuntu18.04
 - org0 - 172.16.206.164
- org1 - 172.16.206.165

Here is host.yaml:
```
---
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
  vars:
    global_domain: example.com
    global_chaincode_lang: golang # Programming language of chaincode
    global_chaincode_version: 1.0 # Your chaincode version
    global_channels:
      - name: common # Channel name
        particapants: # Organizations, should be included in channel
          - org0
          - org1
        chaincode: # Chaincode params
          name: reference
          version: "{{ global_chaincode_version }}"
          policy: ""
          init: '{"Args":["init","a","100","b","100"]}'
    orderer_count: 2 # Amount of orderers in network
  children:
    nodes:
      hosts:
        org0.example.com: # Describes which containers will run on this node
          node_roles:
            - root_orderer # This node will be used to generate crypto-config for other orderers
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - root_peer # This node will be used to create channels and instantiate chaincode
            - explorer # This node will serve hyperledger fabric explorer
          org: org0 # Organization name
          orderer_id: 0
          ansible_host: 172.16.206.164 # Real ip address or domain name of the machine
          ansible_user: oc  # User with sudo access
          #ansible_private_key_file: ~/path-to-private-key # Private key to identify ourselves
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
        # Same structure for any other nodes
        org1.example.com:
          node_roles:
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - explorer
          org: org1
          orderer_id: 1 # ID of orderer-service which is running on this host
          ansible_host: 172.16.206.165
          ansible_user: oc
          #ansible_private_key_file: ~/path-to-private-key
          ansible_ssh_port: 22

```

I already done the `install python, dependencies` part.

When `ansible-playbook config-network.yml -i hosts_raft.yml --ask-become-pass`
it stuck at `TASK [Start docker containers]` for like 1 hour, in org0 and org1, both "hyperledger/fabric-orderer" and "hyperledger/fabric-tools" are running.

org0:
```
oc@ubuntu:~/hl-demo/dockercompose$ sudo docker ps -a
CONTAINER ID        IMAGE                              COMMAND             CREATED             STATUS              PORTS                    NAMES
1caa36cf8bb2        hyperledger/fabric-orderer:1.4.4   "orderer"           9 minutes ago       Up 9 minutes        0.0.0.0:7050->7050/tcp   orderer0.example.com
f3af19c47517        hyperledger/fabric-tools:1.4.4     "/bin/bash"         9 minutes ago       Up 9 minutes                                 cli.example.com

oc@ubuntu:~/hl-demo/dockercompose$ ps -ef | grep docker
root      37513      1  0 May16 ?        00:00:07 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      54360  16058  0 00:06 ?        00:00:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/f3af19c47517bdc6347ddf7e65cc8284b81d319e443c1ed20cac8de07687587c -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
root      54374  37513  0 00:06 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 7050 -container-ip 172.18.0.2 -container-port 7050
root      54399  16058  0 00:06 ?        00:00:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/1caa36cf8bb204c383cf053a7d618970816f27cc82aab70dd112dbf813f8616d -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
oc        54890  54889  0 00:06 pts/1    00:00:00 bash -c docker-compose -f /home/oc/hl-demo/dockercompose/docker-compose-org0.yaml up -d 2>&1
oc        54891  54890  0 00:06 pts/1    00:00:00 docker-compose -f /home/oc/hl-demo/dockercompose/docker-compose-org0.yaml up -d
oc        54892  54891  0 00:06 pts/1    00:00:00 docker-compose -f /home/oc/hl-demo/dockercompose/docker-compose-org0.yaml up -d
oc        55899   2087  0 00:09 pts/0    00:00:00 grep --color=auto docker

```

org1:
```
oc@ubuntu:~/hl-demo$ sudo docker ps -a
CONTAINER ID        IMAGE                              COMMAND             CREATED             STATUS              PORTS                    NAMES
c4de0ef88473        hyperledger/fabric-tools:1.4.4     "/bin/bash"         11 minutes ago      Up 11 minutes                                cli.example.com
3dec6b5182e8        hyperledger/fabric-orderer:1.4.4   "orderer"           11 minutes ago      Up 11 minutes       0.0.0.0:7050->7050/tcp   orderer1.example.com

oc@ubuntu:~/hl-demo$ ps -ef | grep docker
root      21041      1  0 May16 ?        00:00:36 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      53774  16699  0 00:06 ?        00:00:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/c4de0ef8847363a29047d41e60e7eac1712625dd6f9ea1ffe3f266a38121f2b5 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
root      53792  21041  0 00:06 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 7050 -container-ip 172.18.0.2 -container-port 7050
root      53800  16699  0 00:06 ?        00:00:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/3dec6b5182e882cfe41a58e613a5a9b0d8b2772cb41969e10ffabb2487b4df7d -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
oc        54303  54302  0 00:06 pts/1    00:00:00 bash -c docker-compose -f /home/oc/hl-demo/dockercompose/docker-compose-org1.yaml up -d 2>&1
oc        54304  54303  0 00:06 pts/1    00:00:00 docker-compose -f /home/oc/hl-demo/dockercompose/docker-compose-org1.yaml up -d
oc        54305  54304  0 00:06 pts/1    00:00:00 docker-compose -f /home/oc/hl-demo/dockercompose/docker-compose-org1.yaml up -d
oc        54561   2129  0 00:09 pts/0    00:00:00 grep --color=auto docker

```
