### ISSUE TITLE
Explorer is not working {Unexpected token } in JSON at position 799}

### ISSUE THREAD

**Issue by kshitijk83** [Altoros/Ansible-Fabric-Starter#16]
I noticed that the explorer docker container kept restarting every 1 minute:
```
beast@main:~$ docker ps
CONTAINER ID        IMAGE                                                                                                       COMMAND                  CREATED             STATUS                          PORTS                    NAMES
17783c07a9fc        hyperledger/explorer:0.3.9.4                                                                                "/bin/sh -c 'node $E…"   10 minutes ago      Restarting (1) 16 seconds ago                            explorer.org0.example.com
cc74e58a1d65        hyperledger/explorer-db:0.3.9.4                                                                             "docker-entrypoint.s…"   10 minutes ago      Up 10 minutes                   5432/tcp                 explorer-db.org0.example.com
93d89bd32d0d        dev-peer0.org0.example.com-reference-1.0-cd3df0bebe36ac7474d1d33bdfaabe7c65f9a5da0660e4a583b0a65c3c94c848   "/bin/sh -c 'cd /usr…"   28 minutes ago      Up 28 minutes                                            dev-peer0.org0.example.com-reference-1.0
fc359dee6413        dockeraltoros/fabric-rest:latest                                                                            "sh -c 'npm start'"      29 minutes ago      Up 29 minutes                   0.0.0.0:4000->4000/tcp   api.org0.example.com
034204504e63        hyperledger/fabric-peer:1.4.4                                                                               "peer node start"        29 minutes ago      Up 29 minutes                   0.0.0.0:7051->7051/tcp   peer0.org0.example.com
d3c7edbe9def        hyperledger/fabric-tools:1.4.4                                                                              "/bin/bash"              30 minutes ago      Up 29 minutes                                            cli.example.com
71ccccf34f74        hyperledger/fabric-ca:1.4.4                                                                                 "sh -c 'fabric-ca-se…"   30 minutes ago      Up 29 minutes                   0.0.0.0:7054->7054/tcp   ca.org0.example.com
772a985c99c0        hyperledger/fabric-tools:1.4.4                                                                              "/bin/bash"              30 minutes ago      Up 29 minutes                                            cli.org0.example.com
76fcd3da970f        hyperledger/fabric-tools:1.4.4                                                                              "/bin/bash"              30 minutes ago      Up 30 minutes                                            cliNoCryptoVolume.org0.example.com
51c228dc7579        hyperledger/fabric-orderer:1.4.4                                                                            "orderer"                30 minutes ago      Up 30 minutes                   0.0.0.0:7050->7050/tcp   orderer0.example.com
```
Here is the log file:
```
beast@main:~$ docker logs explorer.org0.example.com
false 'ssl-certs' '/opt/explorer/ssl-certs'
postgres://hppoc:password032@db:5432/fabricexplorer
error when connecting to db: { Error: connect ECONNREFUSED 172.19.0.10:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.19.0.10',
  port: 5432 }
******* Initialization started for hyperledger fabric platform ******, { 'first-network': 
   { name: 'first-network',
     profile: './connection-profile/first-network.json' } }
 client_configs.name  first-network  client_configs.profile  ./connection-profile/first-network.json
FabricUtils.createFabricClient 

 ********* call to initializeDetachClient **********
initializeDetachClient --> client_config  { name: 'first-network',
  profile: './connection-profile/first-network.json' }  name  first-network
FabricUtils.createDetachClient 
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
SyntaxError: Unexpected token } in JSON at position 799
    at JSON.parse (<anonymous>)
    at FabricConfig.initialize (/opt/explorer/app/platform/fabric/FabricConfig.js:31:22)
    at FabricClient.initializeDetachClient (/opt/explorer/app/platform/fabric/FabricClient.js:198:16)
    at FabricClient.initialize (/opt/explorer/app/platform/fabric/FabricClient.js:176:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)


Please open web browser to access ：http://localhost:8080/


pid is 6


error when connecting to db: TypeError: Cannot read property 'on' of undefined
    at Timeout.handleDisconnect [as _onTimeout] (/opt/explorer/app/persistence/postgreSQL/PgService.js:68:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
TypeError: "callback" argument must be a function
    at setTimeout (timers.js:450:11)
    at Timeout.handleDisconnect [as _onTimeout] (/opt/explorer/app/persistence/postgreSQL/PgService.js:85:5)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Received kill signal, shutting down gracefully
<<<<<<<<<<<<<<<<<<<<<<<<<< Closing explorer  >>>>>>>>>>>>>>>>>>>>>
Closed out connections
false 'ssl-certs' '/opt/explorer/ssl-certs'
postgres://hppoc:password032@db:5432/fabricexplorer
******* Initialization started for hyperledger fabric platform ******, { 'first-network': 
   { name: 'first-network',
     profile: './connection-profile/first-network.json' } }
 client_configs.name  first-network  client_configs.profile  ./connection-profile/first-network.json
FabricUtils.createFabricClient 

 ********* call to initializeDetachClient **********
initializeDetachClient --> client_config  { name: 'first-network',
  profile: './connection-profile/first-network.json' }  name  first-network
FabricUtils.createDetachClient 
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
SyntaxError: Unexpected token } in JSON at position 799
    at JSON.parse (<anonymous>)
    at FabricConfig.initialize (/opt/explorer/app/platform/fabric/FabricConfig.js:31:22)
    at FabricClient.initializeDetachClient (/opt/explorer/app/platform/fabric/FabricClient.js:198:16)
    at FabricClient.initialize (/opt/explorer/app/platform/fabric/FabricClient.js:176:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)


Please open web browser to access ：http://localhost:8080/


pid is 6


Received kill signal, shutting down gracefully
<<<<<<<<<<<<<<<<<<<<<<<<<< Closing explorer  >>>>>>>>>>>>>>>>>>>>>
Closed out connections
false 'ssl-certs' '/opt/explorer/ssl-certs'
postgres://hppoc:password032@db:5432/fabricexplorer
******* Initialization started for hyperledger fabric platform ******, { 'first-network': 
   { name: 'first-network',
     profile: './connection-profile/first-network.json' } }
 client_configs.name  first-network  client_configs.profile  ./connection-profile/first-network.json
FabricUtils.createFabricClient 

 ********* call to initializeDetachClient **********
initializeDetachClient --> client_config  { name: 'first-network',
  profile: './connection-profile/first-network.json' }  name  first-network
FabricUtils.createDetachClient 
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
SyntaxError: Unexpected token } in JSON at position 799
    at JSON.parse (<anonymous>)
    at FabricConfig.initialize (/opt/explorer/app/platform/fabric/FabricConfig.js:31:22)
    at FabricClient.initializeDetachClient (/opt/explorer/app/platform/fabric/FabricClient.js:198:16)
    at FabricClient.initialize (/opt/explorer/app/platform/fabric/FabricClient.js:176:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)


Please open web browser to access ：http://localhost:8080/


pid is 6


Received kill signal, shutting down gracefully
<<<<<<<<<<<<<<<<<<<<<<<<<< Closing explorer  >>>>>>>>>>>>>>>>>>>>>
Closed out connections
false 'ssl-certs' '/opt/explorer/ssl-certs'
postgres://hppoc:password032@db:5432/fabricexplorer
******* Initialization started for hyperledger fabric platform ******, { 'first-network': 
   { name: 'first-network',
     profile: './connection-profile/first-network.json' } }
 client_configs.name  first-network  client_configs.profile  ./connection-profile/first-network.json
FabricUtils.createFabricClient 

 ********* call to initializeDetachClient **********
initializeDetachClient --> client_config  { name: 'first-network',
  profile: './connection-profile/first-network.json' }  name  first-network
FabricUtils.createDetachClient 
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
SyntaxError: Unexpected token } in JSON at position 799
    at JSON.parse (<anonymous>)
    at FabricConfig.initialize (/opt/explorer/app/platform/fabric/FabricConfig.js:31:22)
    at FabricClient.initializeDetachClient (/opt/explorer/app/platform/fabric/FabricClient.js:198:16)
    at FabricClient.initialize (/opt/explorer/app/platform/fabric/FabricClient.js:176:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)


Please open web browser to access ：http://localhost:8080/


pid is 6


Received kill signal, shutting down gracefully
<<<<<<<<<<<<<<<<<<<<<<<<<< Closing explorer  >>>>>>>>>>>>>>>>>>>>>
```
I connected all 4 VMs with deafult configuration, here's the host_raft.yml file:
```
beast@main:~$ cat Ansible-Fabric-Starter/hosts_raft.yml 
---
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
  vars:
    global_domain: example.com
    global_chaincode_lang: node # Programming language of chaincode
    global_chaincode_version: 1.0 # Your chaincode version
    global_channels:
      - name: common # Channel name
        particapants: # Organizations, should be included in channel
          - org0
          - org1
          - org2
          - org3
        chaincode: # Chaincode params
          name: reference
          version: "{{ global_chaincode_version }}"
          policy: ""
          init: '{"Args":["init","a","100","b","100"]}'
      - name: bilateral-1 # Channel name
        particapants: # Organizations, should be included in channel
          - org2
          - org3
        chaincode: # Chaincode params
          name: relationship
          version: "{{ global_chaincode_version }}"
          policy: ""
          init: '{"Args":["init","a","100","b","100"]}'
    orderer_count: 4 # Amount of orderers in network
  children:
    nodes:
      hosts:
        org0.example.com: # Describes which containers will run on this node
          node_roles:
            - root_orderer # This node will be used to generate crypto-config for other orderers
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - root_peer # This node will be used to create channels and instantiate chaincode
            - explorer # This node will serve hyperledger fabric explorer
          org: org0 # Organization name
          orderer_id: 0
          ansible_host: 35.222.117.109 # Real ip address or domain name of the machine
          ansible_user: beast  # User with sudo access
          ansible_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
        # Same structure for any other nodes
        org1.example.com:
          node_roles:
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - explorer
          org: org1
          orderer_id: 1 # ID of orderer-service which is running on this host
          ansible_host: 34.72.49.26
          ansible_user: beast
          ansible_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_port: 22
        org2.example.com:
          node_roles:
            - orderer
            - peer
            - explorer
          org: org2
          orderer_id: 2
          ansible_host: 104.154.197.7
          ansible_user: beast
          ansible_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_port: 22
        org3.example.com: # This node will host only kafka-broker and peer.
          node_roles:
            - peer
            - orderer
            - explorer
          org: org3
          orderer_id: 3
          ansible_host: 35.238.180.128
          ansible_user: beast
          ansible_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_port: 22
```
I just changed this `hosts_raft.yml` file only, network was deployed to all orgs successfully.
`ansible-playbook start-explorer.yml -i hosts_raft.yml` is also not giving any error
System info:
- ubuntu 18.04
- fabric 1.4.7
